### PR TITLE
Made a method for to get a users subscriptions to populate the add pe…

### PR DESCRIPTION
**Pull request by DanHoganRed**
…rk dropdown menu. I will add a test for this when the AjaxControllerTests PR gets merged.
Resolves issue #24

### CODE REVIEW

**Comment by raymondwu1** [comment]
Looks like a previous pull request made some conflicts with this PR

**Comment by raymondwu1** [comment]
Should probably keep the changes on master since this one uses an older version

**Comment by DanHoganRed** [comment]
Resolved conflicts.

**Comment by raymondwu1** [comment]
cool thanks

**Pull request merged**
