### PR TITLE
Html errors 

### PR DESCRIPTION
**Pull request by Soluzochukwu**
Little changes in login and registration (changes the password fields type to "password")
Added error pages added (for login, registration and forgot password)

### CODE REVIEW

**Comment by raymondwu1** [comment]
You should try to add tests for your new methods in the user controller

**Comment by DanHoganRed** [comment]
capture

This breaks when you try to reset the password. Additionally you should add tests to the controllers if you change the controllers.

**Comment by DanHoganRed** [comment]
Also do not commit .iml files

**Comment by Soluzochukwu** [comment]
I added tests and fixed the issues

**Review by omaribrahim4 — APPROVED** [review]
Works as expected. Good Job.

**Comment by raymondwu1** [comment]
looks good nice

**Pull request merged**
